server {
    listen 80;
    server_name localhost;

    # Directorio donde están los archivos compilados de React
    root /usr/share/nginx/html;
    index index.html;

    # Regla más importante: para que React Router funcione.
    # Si alguien pide /dashboard, Nginx le sirve index.html
    # y React Router se encarga del resto internamente.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso: todas las peticiones que empiecen con /api
    # se redirigen al contenedor del backend (usando su nombre DNS interno)
    location /api/ {
        proxy_pass         http://backend:4000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
